/**
 * Názvy oddílů CZ-NACE Rev. 2 (dvoumístné kódy) dle klasifikace ČSÚ.
 * Zobrazujeme název oddílu, do kterého kód patří — ne vlastní popisy.
 */
export const NACE_DIVISIONS: Readonly<Record<string, string>> = {
  "01": "Rostlinná a živočišná výroba, myslivost a související činnosti",
  "02": "Lesnictví a těžba dřeva",
  "03": "Rybolov a akvakultura",
  "05": "Těžba a úprava černého a hnědého uhlí",
  "06": "Těžba ropy a zemního plynu",
  "07": "Těžba a úprava rud",
  "08": "Ostatní těžba a dobývání",
  "09": "Podpůrné činnosti při těžbě",
  "10": "Výroba potravinářských výrobků",
  "11": "Výroba nápojů",
  "12": "Výroba tabákových výrobků",
  "13": "Výroba textilií",
  "14": "Výroba oděvů",
  "15": "Výroba usní a souvisejících výrobků",
  "16": "Zpracování dřeva, výroba dřevěných, korkových, proutěných a slaměných výrobků, kromě nábytku",
  "17": "Výroba papíru a výrobků z papíru",
  "18": "Tisk a rozmnožování nahraných nosičů",
  "19": "Výroba koksu a rafinovaných ropných produktů",
  "20": "Výroba chemických látek a chemických přípravků",
  "21": "Výroba základních farmaceutických výrobků a farmaceutických přípravků",
  "22": "Výroba pryžových a plastových výrobků",
  "23": "Výroba ostatních nekovových minerálních výrobků",
  "24": "Výroba základních kovů, hutní zpracování kovů; slévárenství",
  "25": "Výroba kovových konstrukcí a kovodělných výrobků, kromě strojů a zařízení",
  "26": "Výroba počítačů, elektronických a optických přístrojů a zařízení",
  "27": "Výroba elektrických zařízení",
  "28": "Výroba strojů a zařízení j. n.",
  "29": "Výroba motorových vozidel (kromě motocyklů), přívěsů a návěsů",
  "30": "Výroba ostatních dopravních prostředků a zařízení",
  "31": "Výroba nábytku",
  "32": "Ostatní zpracovatelský průmysl",
  "33": "Opravy a instalace strojů a zařízení",
  "35": "Výroba a rozvod elektřiny, plynu, tepla a klimatizovaného vzduchu",
  "36": "Shromažďování, úprava a rozvod vody",
  "37": "Činnosti související s odpadními vodami",
  "38": "Shromažďování, sběr a odstraňování odpadů, úprava odpadů k dalšímu využití",
  "39": "Sanace a jiné činnosti související s odpady",
  "41": "Výstavba budov",
  "42": "Inženýrské stavitelství",
  "43": "Specializované stavební činnosti",
  "45": "Velkoobchod, maloobchod a opravy motorových vozidel",
  "46": "Velkoobchod, kromě motorových vozidel",
  "47": "Maloobchod, kromě motorových vozidel",
  "49": "Pozemní a potrubní doprava",
  "50": "Vodní doprava",
  "51": "Letecká doprava",
  "52": "Skladování a vedlejší činnosti v dopravě",
  "53": "Poštovní a kurýrní činnosti",
  "55": "Ubytování",
  "56": "Stravování a pohostinství",
  "58": "Vydavatelské činnosti",
  "59": "Činnosti v oblasti filmů, videozáznamů a televizních programů, pořizování zvukových nahrávek a hudební vydavatelské činnosti",
  "60": "Tvorba programů a vysílání",
  "61": "Telekomunikační činnosti",
  "62": "Činnosti v oblasti informačních technologií",
  "63": "Informační činnosti",
  "64": "Finanční zprostředkování, kromě pojišťovnictví a penzijního financování",
  "65": "Pojištění, zajištění a penzijní financování, kromě povinného sociálního zabezpečení",
  "66": "Ostatní finanční činnosti",
  "68": "Činnosti v oblasti nemovitostí",
  "69": "Právní a účetnické činnosti",
  "70": "Činnosti vedení podniků; poradenství v oblasti řízení",
  "71": "Architektonické a inženýrské činnosti; technické zkoušky a analýzy",
  "72": "Výzkum a vývoj",
  "73": "Reklama a průzkum trhu",
  "74": "Ostatní profesní, vědecké a technické činnosti",
  "75": "Veterinární činnosti",
  "77": "Činnosti v oblasti pronájmu a operativního leasingu",
  "78": "Činnosti související se zaměstnáním",
  "79": "Činnosti cestovních agentur, kanceláří a jiné rezervační a související činnosti",
  "80": "Bezpečnostní a pátrací činnosti",
  "81": "Činnosti související se stavbami a úpravou krajiny",
  "82": "Administrativní, kancelářské a jiné podpůrné činnosti pro podnikání",
  "84": "Veřejná správa a obrana; povinné sociální zabezpečení",
  "85": "Vzdělávání",
  "86": "Zdravotní péče",
  "87": "Pobytové služby sociální péče",
  "88": "Ambulantní nebo terénní sociální služby",
  "90": "Tvůrčí, umělecké a zábavní činnosti",
  "91": "Činnosti knihoven, archivů, muzeí a jiných kulturních zařízení",
  "92": "Činnosti heren, kasin a sázkových kanceláří",
  "93": "Sportovní, zábavní a rekreační činnosti",
  "94": "Činnosti organizací sdružujících osoby za účelem prosazování společných zájmů",
  "95": "Opravy počítačů a výrobků pro osobní potřebu a převážně pro domácnost",
  "96": "Poskytování ostatních osobních služeb",
  "97": "Činnosti domácností jako zaměstnavatelů domácího personálu",
  "98": "Činnosti domácností produkujících blíže neurčené výrobky a služby pro vlastní potřebu",
  "99": "Činnosti exteritoriálních organizací a orgánů",
};

export function naceDivisionLabel(code: string): string | null {
  const d = code.replace(/\D/g, "").slice(0, 2);
  return NACE_DIVISIONS[d] ?? null;
}
